Dante/urls.py
#TENEMOS QUE REVISAR LAS URLS , ACTUALIZARLAS PORQUE SE INCORPORO USERS 
#TENEMOS QUE CREAR ARCHIVOS URLS.PY EN CADA APP PARA QUE SEAN AUN MAS INDEPENDIENTE Y MAS CLEAN CODE ACA
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.auth.views import logout_then_login,redirect_to_login
from django.conf.urls.static import static
import users.views as users1
from Venta import views as venta
import Inventario.views as Inventario
from inventarioApi import views as Api

urlpatterns = [
    #LOGIN
    path('', Inventario.Home.as_view(), name="home"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('inventario/', include('Inventario.urls')),
    path('user/', include('users.urls')),
    path('api/', include('inventarioApi.urls')),
    path('venta/', include('Venta.urls')),
    path('admin/', admin.site.urls),

]  
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



    

    
    
   
    
   
    

Inventario/models.py
import os
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator,MinLengthValidator
from django.core.exceptions import ValidationError

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=100, validators=[MinLengthValidator(limit_value=1, message="El nombre no puede estar vacío.")])
    descripcion = models.TextField(null=True, default=None, validators=[MinLengthValidator(limit_value=1)])

    def generarNombre(instance, filename):
        extension = os.path.splitext(filename)[1][1:]
        ruta = 'categorias'
        fecha = timezone.now().strftime("%d%m%Y_%H%M%S")
        nombre = "{}.{}".format(fecha, extension)
        return os.path.join(ruta, nombre)

    foto = models.ImageField(upload_to=generarNombre, null=True, default='categorias/categoria.png')

    def __str__(self):
        return self.name
    
class Suppliers(models.Model):
    name=models.CharField(max_length=100)
    run=models.CharField(max_length=10)
    cellphone=models.PositiveIntegerField()
    email=models.EmailField()

    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=100,verbose_name=("Name"))
    name_category=models.ForeignKey("Inventario.Category", verbose_name=("Name Category"), on_delete=models.CASCADE)
    price_sold=models.PositiveIntegerField(verbose_name=("Price Sold"))
    buy_price=models.PositiveIntegerField(verbose_name=("Buy Price"))
    stock=models.PositiveIntegerField(verbose_name=("Stock"))
    bar_code=models.IntegerField(verbose_name=("Bar Code"))
    minimum_amount=models.PositiveIntegerField(verbose_name=("Minimum Amount"))
    suppliers=models.ForeignKey("Inventario.Suppliers", verbose_name=("Suppliers"), on_delete=models.PROTECT)

    def generarNombre(instance, filename):
        extension = os.path.splitext(filename)[1][1:]
        ruta = 'productos'
        fecha = timezone.now().strftime("%d%m%Y_%H%M%S")
        nombre = "{}.{}".format(fecha, extension)
        return os.path.join(ruta, nombre)

    imagen = models.ImageField(upload_to=generarNombre, null=True, default='productos/producto.png')
    # def clean(self):
         
    #     # Realiza validaciones adicionales al limpiar los datos del modelo.
    #     # En este caso, asegura que el precio de venta sea mayor que el precio de compra.
    
        # if self.price_sold <= self.buy_price:
        #     raise ValidationError('El precio de venta debe ser mayor que el precio de compra.')
    
    def actualizar_stock_venta(self, cantidad):
        if self.stock >= cantidad:
            self.stock -= cantidad
            self.save()
        else:
            raise ValidationError('No hay suficiente stock disponible para realizar la venta.')

    def __str__(self):
        return self.name
    
class Descuento(models.Model):
    producto = models.ForeignKey('Product', on_delete=models.CASCADE)
    name_descuento = models.CharField(max_length=100, verbose_name="Nombre Descuento")
    valor_descuento = models.DecimalField(max_digits=5, decimal_places=2, help_text="Porcentaje de descuento")

    def __str__(self):
        return self.name_descuento

    class Meta:
        verbose_name = "Descuento"
        verbose_name_plural = "Descuentos"
        ordering = ["id"]

Venta/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from Inventario.models import Product, Descuento



# Create your models here.


class Cajas(models.Model):
    vendedor = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    monto_inicial = models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name="Monto Inicial")
    cantidad_vendida = models.DecimalField(default=0, max_digits=10, decimal_places=2, verbose_name="Cantidad Vendida")
    fecha_apertura = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de Apertura")
    fecha_cierre = models.DateTimeField(null=True, blank=True, verbose_name="Fecha de Cierre")
    cerrada = models.BooleanField(default=False, verbose_name="Caja Cerrada")

    def __str__(self):
        return f"Caja {self.id} - {self.vendedor.username}"

    def abrir_caja(self):
        self.cerrada = False
        self.save()

    def cerrar_caja(self):
        self.cerrada = True
        self.fecha_cierre = timezone.now()
        self.save()
    @property
    def turno_abierto(self):
        return not self.cerrada
class Venta(models.Model):
    fecha = models.DateTimeField(auto_now_add=True)
    caja = models.ForeignKey(Cajas, on_delete=models.CASCADE, default=1)
    # total_venta = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    
    def __str__(self):
        return f"Venta {self.id} - {self.fecha}"

class DetalleVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE, related_name='detalles')
    producto = models.ForeignKey(Product, related_name='detalles', on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    descuento = models.ForeignKey(Descuento, on_delete=models.SET_NULL, null=True, blank=True)


    def calcular_subtotal(self):
        
        return self.precio * self.cantidad


class Reporte(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    nombre = models.CharField(max_length=100, verbose_name="Nombre del Reporte", db_index=True)
    descripcion = models.TextField(null=True, blank=True, verbose_name="Descripción del Reporte")
    datos = models.JSONField(default=dict, verbose_name="Datos del Reporte")

    class Meta:
        indexes = [
            models.Index(fields=['nombre'], name='idx_nombre_length'),
        ]

    def __str__(self):
        return self.nombre

users/models.py
from django.db import models
from django.contrib.auth.models import  AbstractUser,User, BaseUserManager

# Create your models here.
class UserManager(BaseUserManager):
    def _create_user(self, username, rut, first_name,password,is_staff,is_superuser,**extra_fields): 
        user= self.model(
            username=username,
            rut=rut,
            first_name=first_name,
            is_staff=is_staff,
            is_superuser=is_superuser,
            **extra_fields

        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self,username,rut,first_name,password=None,**extra_fields):
        return self._create_user(username,rut,first_name,password,False,False,**extra_fields)
    
    def create_superuser(self,username,rut,first_name,password=None,**extra_fields):
        return self._create_user(username,rut,first_name,password,True,True,**extra_fields)
     


class User(AbstractUser):
    username= models.CharField('Nombre de Usuario', unique=True, max_length=100)
    first_name= models.CharField('Nombres', max_length=200, blank=True, null=True)
    last_name= models.CharField('Apellidos', max_length=200, blank=True, null=True)
    is_active= models.BooleanField(default=True)
    is_staff=models.BooleanField(default=False)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    rut = models.CharField(max_length=12, unique=True, null=True, blank=True)
    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['rut', 'first_name', 'last_name']

    def __str__(self) :
        return f'{self.first_name}, {self.last_name}'
    

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Mundo Infantil</title>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
    integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" href="{% static 'css/inventario/base.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
    crossorigin="anonymous"></script>
  {% block css %}
  {% endblock css %}
</head>

<body>
  {%block nav%}
  <nav class="navbar navbar-expand-md sticky-md-top">
    <div class="container-fluid">
      <img src="/media/logo.svg" height="65" alt="">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <ul class="nav justify-content-start"> <!-- Elementos iniciales -->
            <li class="nav-item">
              <a class="nav-link text-light  " aria-current="page" href="{% url 'home'%}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link text-light  dropdown-toggle" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Inventario
              </a>
              <ul class="dropdown-menu">
                {%if perms.Inventario.view_category%}
                <li class="nav-item">
                  <a class="nav-link " href="{% url 'categorias' %}">Categorías</a>
                </li>
                {%endif%}
                {% if perms.Inventario.view_suppliers %}
                <li class="nav-item">
                  <a class="nav-link " href="{% url 'proveedores' %}">Proveedor</a>
                </li>
                {%endif%}
                {% if perms.Venta.add_user %}

                <li>
                  <hr class="dropdown-divider">
                </li>
                <li class="nav-item">
                  <a href="{% url 'usuarios' %}" class="nav-link ">Usuario</a>
                </li>
                {% endif %}


              </ul>
            </li>
            {%endif%}



            {% if perms.Venta.view_venta %}
            <li class="nav-item">
              <a class="nav-link text-light" href="{% url 'panelVenta' %}">Venta</a>
            </li>


            <li class="nav-item">
              <a class="nav-link disabled" aria-disabled="true">Caja</a>
            </li>
            {%endif%}
          </ul>
        </div>
      </div>
      <div class="navbar-nav ml-auto  d-none d-md-block"> <!-- Elementos alineados a la derecha -->
        {% if user.is_authenticated %}
        <li class="nav-item ">
          <a href="" class="nav-link text-warning disabled">Usuario: <b>{{user.username}}</b></a>
        </li>
        <li class="nav-item ">
          <a href="{% url 'cambiar_password' %}" class="   ">Cambiar Contraseña</a>
        </li>
        <li class="nav-item ">
          <a href="{% url 'logout' %}" class=" btn btn-info  ">Cerrar Sesión</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a href="{% url 'login' %}" class="btn btn-info ">Iniciar Sesión</a>
        </li>

        {% endif %}
      </div>
    </div>
  </nav>


  {%endblock nav%}

  {% block content %}
  <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="true">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="/media/welcome.jpg" class="d-block w-100" alt="..." height="400px">
      </div>
      <div class="carousel-item ">
        <img src="/media/fonde2.jpg" class="d-block w-100" alt="..." height="400px">
      </div>

      <div class="carousel-item">
        <img src="/media/fondo.svg" class="d-block w-100" alt="..." height="400px">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying"
      data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying"
      data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-6">
          <h4 class="h4">Contacto</h4>
          <p><i class="fas fa-map-marker-alt"></i> Dirección: 123 Calle Ficticia, Colonia Imaginaria, Ciudad Irreal,
            Estado de los Sueños, Código Postal: 12345, País de la Imaginación.</p>
          <p><i class="fas fa-phone"></i> Teléfono: +595 6995821</p>
          <p><i class="fas fa-envelope"></i> Correo: Soporte@sistemaventainventario.com</p>
        </div>

        <div class="col-lg-4">
          <h4 class="h4">Síguenos</h4>
          <ul class="list-unstyled">
            <li><a href="#"><i class="fab fa-facebook"></i> Facebook</a></li>
            <li><a href="#"><i class="fab fa-twitter"></i> Twitter</a></li>
            <li><a href="#"><i class="fab fa-linkedin"></i> LinkedIn</a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <p class="text-center">© 2023 SystemInventory. Todos los derechos reservados.</p>
        </div>
      </div>
    </div>
  </footer>
  {% endblock content %}


</body>
{% if messages %}
{% for m in messages %}
<script>

  Swal.fire({
    title: 'Mensaje',
    text: "{{ message }}",
    icon: 'success',
    confirmButtonText: 'Ok'
  });


</script>
{% endfor %}
{%endif%}
{%block extrajs%}

{%endblock extrajs%}

</html>