Dante/urls.py
#TENEMOS QUE REVISAR LAS URLS , ACTUALIZARLAS PORQUE SE INCORPORO USERS 
#TENEMOS QUE CREAR ARCHIVOS URLS.PY EN CADA APP PARA QUE SEAN AUN MAS INDEPENDIENTE Y MAS CLEAN CODE ACA
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.auth.views import logout_then_login,redirect_to_login
from django.conf.urls.static import static
import users.views as users1
from Venta import views as venta
import Inventario.views as Inventario
from inventarioApi import views as Api

urlpatterns = [
    #LOGIN
    path('', Inventario.Home.as_view(), name="home"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('inventario/', include('Inventario.urls')),
    path('user/', include('users.urls')),
    path('api/', include('inventarioApi.urls')),
    path('venta/', include('Venta.urls')),
    path('admin/', admin.site.urls),

]  
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



    

    
    
   
    
   
    

Inventario/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('categorias/',Categorias.as_view(), name="categorias"),
    path('proveedores/',ListaProveedores.as_view(), name='proveedores'),
    path('categorias/list/<str:nombre>/', ListaProductosView.as_view(), name="listaProductos"),
    path('productos/edit/<int:pk>',ProductoEdicion.as_view(),name='editarProducto'),
    path('categorias/edit/<int:pk>',CategoriaEdicion.as_view(),name='editarCategoria'),
    path('proveedor/edit/<int:pk>',ProveedorEdicion.as_view(),name='editarProveedor'),
    path('productos/eliminado/<int:pk>/',ProductoEliminar.as_view(),name='eliminarProducto'),
    path('categorias/eliminado/<int:pk>/',CategoriaEliminar.as_view(),name='eliminarCategoria'),
    path('proveedor/eliminado/<int:pk>/',ProveedorEliminar.as_view(),name='elimminarProveedor'),
]

Inventario/models.py
import os
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator,MinLengthValidator
from django.core.exceptions import ValidationError

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=100, validators=[MinLengthValidator(limit_value=1, message="El nombre no puede estar vacío.")])
    descripcion = models.TextField(null=True, default=None, validators=[MinLengthValidator(limit_value=1)])

    def generarNombre(instance, filename):
        extension = os.path.splitext(filename)[1][1:]
        ruta = 'categorias'
        fecha = timezone.now().strftime("%d%m%Y_%H%M%S")
        nombre = "{}.{}".format(fecha, extension)
        return os.path.join(ruta, nombre)

    foto = models.ImageField(upload_to=generarNombre, null=True, default='categorias/categoria.png')

    def __str__(self):
        return self.name
    
class Suppliers(models.Model):
    name=models.CharField(max_length=100)
    run=models.CharField(max_length=10)
    cellphone=models.PositiveIntegerField()
    email=models.EmailField()

    def __str__(self):
        return self.name

class Product(models.Model):
    name=models.CharField(max_length=100,verbose_name=("Name"))
    name_category=models.ForeignKey("Inventario.Category", verbose_name=("Name Category"), on_delete=models.CASCADE)
    price_sold=models.PositiveIntegerField(verbose_name=("Price Sold"))
    buy_price=models.PositiveIntegerField(verbose_name=("Buy Price"))
    stock=models.PositiveIntegerField(verbose_name=("Stock"))
    bar_code=models.IntegerField(verbose_name=("Bar Code"))
    minimum_amount=models.PositiveIntegerField(verbose_name=("Minimum Amount"))
    suppliers=models.ForeignKey("Inventario.Suppliers", verbose_name=("Suppliers"), on_delete=models.PROTECT)

    def generarNombre(instance, filename):
        extension = os.path.splitext(filename)[1][1:]
        ruta = 'productos'
        fecha = timezone.now().strftime("%d%m%Y_%H%M%S")
        nombre = "{}.{}".format(fecha, extension)
        return os.path.join(ruta, nombre)

    imagen = models.ImageField(upload_to=generarNombre, null=True, default='productos/producto.png')
    # def clean(self):
         
    #     # Realiza validaciones adicionales al limpiar los datos del modelo.
    #     # En este caso, asegura que el precio de venta sea mayor que el precio de compra.
    
        # if self.price_sold <= self.buy_price:
        #     raise ValidationError('El precio de venta debe ser mayor que el precio de compra.')
    
    def actualizar_stock_venta(self, cantidad):
        if self.stock >= cantidad:
            self.stock -= cantidad
            self.save()
        else:
            raise ValidationError('No hay suficiente stock disponible para realizar la venta.')

    def __str__(self):
        return self.name
    
class Descuento(models.Model):
    producto = models.ForeignKey('Product', on_delete=models.CASCADE)
    name_descuento = models.CharField(max_length=100, verbose_name="Nombre Descuento")
    valor_descuento = models.DecimalField(max_digits=5, decimal_places=2, help_text="Porcentaje de descuento")

    def __str__(self):
        return self.name_descuento

    class Meta:
        verbose_name = "Descuento"
        verbose_name_plural = "Descuentos"
        ordering = ["id"]

Inventario/forms.py
from django import forms
from .models import Category, Suppliers, Product




class CategoryForm(forms.ModelForm):
    name = forms.CharField(
        label='Nombre Categoria',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese el nombre de la categoría'}),
        max_length=50,
        required=True,
        help_text='Ingrese el nombre de la categoría.',
        error_messages={'required': 'El campo de Nombre es obligatorio.'}  # Mensaje personalizado para campos requeridos
    )

    descripcion = forms.CharField(
        label='Descripción general',
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ingrese una descripción'}),
        max_length=255,
        required=True,
        help_text='Ingrese una descripción general para la categoría.',
    )

    foto = forms.ImageField(
        required=False,
        label='Imagen referencial',
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        help_text='Seleccione una imagen para la categoría (opcional).',
    )

    def clean_nombre(self):
        nombre = self.cleaned_data.get('nombre')
        if nombre.strip() == '':
            raise forms.ValidationError("El nombre no puede consistir solo de espacios en blanco.")
        return nombre
    

    class Meta:
        model = Category
        fields = '__all__'
        




class SuppliersForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del proveedor'}),
        max_length=100,
    )
    run = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'RUN'}),
        max_length=10,
    )
    cellphone = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Número de teléfono'}),
        max_length=15,
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
    )

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if name.strip() == '':
            raise forms.ValidationError("El nombre no puede consistir solo de espacios en blanco.")
        return name

    class Meta:
        model = Suppliers
        fields = ['name', 'run', 'cellphone', 'email']


class ProductForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre del Producto'}),
        max_length=100,
    )
    name_category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        empty_label="Seleccione una categoria"
    )
    price_sold = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Precio de Venta'}),
    )
    buy_price = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Precio de Compra'}),
    )
    stock = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Stock'}),
    )
    bar_code = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Código de Barras'}),
    )
    minimum_amount = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Cantidad Mínima'}),
    )
    # suppliers = forms.ModelChoiceField(
    #     queryset=Suppliers.objects.all(),
    #     widget=forms.Select(attrs={'class': 'form-control'}),
    # )
    suppliers = forms.ModelChoiceField(
        queryset=Suppliers.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        empty_label="Seleccione un proveedor"  # Agrega esta línea para mostrar un texto por defecto en el select
    )
    imagen = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
    )

    class Meta:
        model = Product
        fields = ['name', 'name_category', 'price_sold', 'buy_price', 'stock', 'bar_code', 'minimum_amount', 'suppliers', 'imagen']

Inventario/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.serializers import serialize
from django.views.generic import TemplateView,ListView,UpdateView, CreateView,DeleteView, View
from django.urls import reverse_lazy
from Inventario.forms import *
from Inventario.models import *
from Venta.models import *
from Venta.forms import *
from .mixins import *


#VISTAS GENERALES PAGINAS PRINCIPALES

class Home(TemplateView):
    template_name='base.html'

# Categorias CRUD

class Categorias(LoginRequiredMixin,View):
    model=Category
    form_class= CategoryForm
    template_name='inventario/Categorias.html'
    def get_queryset(self):
        return self.model.objects.all()
    
    def get_context_data(self, **kwargs):
        context = {}
        context["categorias"] = self.get_queryset()
        context["form"] = self.form_class 
        return context
    
    def get(self,request,*args, **kwargs):  
        return render(request,self.template_name,self.get_context_data())
    
    def post(self,request,*args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('categorias')
        
class CategoriaEdicion(LoginRequiredMixin,UpdateView):
    model = Category
    template_name = 'inventario/mantenedorCategoria.html'
    form_class = CategoryForm
    success_url = reverse_lazy('categorias')

    def form_valid(self, form):
        # Llamamos al método form_valid de la clase base
        response = super().form_valid(form)
        # Agregamos el mensaje de éxito
        messages.success(self.request, "Modificado Correctamente")
        # Retornamos la respuesta
        return response
    
class CategoriaEliminar(LoginRequiredMixin,DeleteView):
    model=Category
    success_url=reverse_lazy('categorias')

    def form_valid(self,form):
        messages.success(self.request, "Eliminado Correctamente")
        return super().form_valid(form)
    
# PROVEEDORES CRUD

class ListaProveedores(LoginRequiredMixin,View):
    model=Suppliers
    form_class= SuppliersForm
    template_name='inventario/proveedores.html'
    def get_queryset(self):
        return self.model.objects.all()
    
    def get_context_data(self, **kwargs):
        context = {}
        context["proveedores"] = self.get_queryset()
        context["form"] = self.form_class
        return context
    
    
    def get(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            data = serialize('json', self.get_queryset())
            return HttpResponse(data, 'application/json')
        else:
            return render(request,self.template_name,self.get_context_data())   
    
    def post(self,request,*args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect('proveedores')
        
class ProveedorEdicion(LoginRequiredMixin,UpdateView):
    model=Suppliers
    form_class=SuppliersForm
    template_name='inventario/mantenedorProveedor.html'
    success_url= reverse_lazy('proveedores')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["proveedores"] = Suppliers.objects.all()
        return context
    
class ProveedorEliminar(LoginRequiredMixin,DeleteView):
    model=Suppliers
    success_url = reverse_lazy('proveedores')

    def form_valid(self,form):
        messages.success(self.request, "Eliminado Correctamente")
        return super().form_valid(form)

# PRODUCTOS CRUD

class ListaProductosView(LoginRequiredMixin, ListView, View):
    model=Product
    form_class= ProductForm
    template_name = 'inventario/listaProductos.html'
    def get_context_data(self, **kwargs):
        context = {}
        nombre_categoria = kwargs.get('nombre')
        
        try:
            context['categorias'] = Category.objects.get(name=nombre_categoria)
        except Category.DoesNotExist:
            # Manejar la categoría que no existe, por ejemplo, redirigir a una página de error
            print(f"Categoría '{nombre_categoria}' no encontrada.")
            context['categorias'] = None  

        context["form"] = self.form_class
        return context

    def get(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            data = serialize('json', self.get_queryset())
            return HttpResponse(data, 'application/json')
        else:
            nombre_categoria = kwargs.get('nombre')
            context = self.get_context_data(nombre_categoria=nombre_categoria)
            return render(request, self.template_name, context)
    def get_queryset(self):
        try:
            nombre_categoria = self.kwargs.get('nombre')
            categoria = Category.objects.get(name=nombre_categoria)
            return Product.objects.filter(name_category=categoria)
        except Category.DoesNotExist as e:
            # Manejar la categoría que no existe e imprimir detalles
            print(f"Error: {e}")
            return Product.objects.none()

    def post(self, request, *args, **kwargs):
        # Manejar la creación de productos aquí
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()

        nombre_categoria = kwargs.get('nombre')
        return redirect('listaProductos', nombre=nombre_categoria)
    
class ProductoEdicion(LoginRequiredMixin,UpdateView):
    model = Product
    template_name = 'inventario/mantenedorProducto.html'
    form_class = ProductForm
    success_url = reverse_lazy('listaProductos', kwargs={'nombre': ''})  

    def form_valid(self, form):
        name_category_value = form.cleaned_data.get('name_category')
        messages.success(self.request, "Modificado Correctamente")
        self.success_url = reverse_lazy('listaProductos', kwargs={'nombre': name_category_value})
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Error al modificar el producto")  # Mensaje de error en caso de formulario no válido
        return super().form_invalid(form)
    

class ProductoEliminar(LoginRequiredMixin,DeleteView):
    model=Product
    success_url=reverse_lazy('listarProducto', kwargs={'nombre': ''})

    def form_valid(self,form):
        messages.success(self.request, "Eliminado Correctamente")
        self.success_url = reverse_lazy('listaProductos', kwargs={'nombre': self.object.name_category.name})
        return super().form_valid(form)

templates/inventario/Categorias.html
{% extends "base.html" %}
{% load static %}
{%block css%}
<link rel="stylesheet" href="{%static 'css/inventario/categorias.css'%}"> {%endblock css%}
{% block content %}
<div class="container mt-6">
    <div class="container text-center mt-5">


        <div class="row ">
            <div class=" form-group col-md-8 mt-2 d-flex justify-content-center align-items-center">
                <h1 class="fst-italic ">Categorias</h1>
            </div>
            {%if perms.Inventario.add_category%}
            <div class="col-md-4 mt-2 d-flex justify-content-end">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#Creacion">
                    Crear Categorias
                </button>
            </div>
            {%endif%}
        </div>

        <div class="mb-5 mt-5 row col-12 justify-content-center">
            {% for c in categorias %}
            <div class="card mx-3 mb-3 shadow border" id="card-{{ forloop.counter }}" style="width: 15rem;">
                {% if c.foto %}
                <img src="{{ c.foto.url }}" class="card-img-top" alt="..." height="150px">
                {% endif %}
                <div class="card-body text-center">
                    <h5 class="card-title">{{ c.name }}</h5>
                    <p class="card-text">{{ c.descripcion }}</p>
                    <a href="{% url 'listaProductos' c.name %}" class="btn btn-3d btn-primary"><i
                            class="fa-solid fa-eye"></i> Ver Listado</a>

                    <div class="form-group mt-2 row">
                        {% if perms.Inventario.change_category %}
                        <a href="{% url 'editarCategoria' c.id %}"
                            class="btn btn-3d btn-warning mr-2 col-7">Modificar</a>
                        {% endif %}

                        {% if perms.Inventario.delete_category %}
                        <a href="{% url 'eliminarCategoria' c.id %}" class="btn btn-3d btn-danger mr-2 col-4"><i
                                class="fa-regular fa-trash-can"></i> </a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <!-- Modal Creacion-->
        <div class="modal fade" id="Creacion" tabindex="-1" aria-labelledby="exampleModalLabel"
            data-bs-backdrop="static" data-bs-keyboard="false" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel"> <strong>Formulario de Registro</strong>
                        </h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" autocomplete="off">
                            {% csrf_token %}
                            {{ form.as_p}}
                            <div class="modal-footer">
                                <a href="{% url 'categorias' %}" class="btn btn-3d btn-dark">Cancelar</a>
                                <button type="submit" class="btn btn-primary">Guardar</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>

        {% endblock content %}

templates/inventario/UserDeleteList.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{%static 'css/inventario/modal.css'%}">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
{% endblock css %}

{% block content %}
<div class="container mt-5">

    <div class="container text-center mt-5">


        <div class="row">
            <div class="col-md-8 mt-2 d-flex">

                <h2 class="fst-italic ">Usuarios</h2>
            </div>
            <div class="col-md-4 mt-2 d-flex justify-content-end">
                <a href="{%url 'usuarios'%}" class="btn btn-primary">Usuarios</a>
            </div>
        </div>
        <div class="table-responsive mt-4">
            <table id="tabla_usuarios" class="table table-bordered table-hover table-striped">
                <thead>
                    <tr>
                        <th>Rut</th>
                        <th>Username</th>
                        <th>Nombre</th>
                        <th>Fecha Nacimiento</th>
                        <th>Grupos</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</div>






{% endblock content%}
{% block extrajs %}
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="{% static 'js/productos/UserDeletes.js' %}"></script>


{% endblock extrajs %}

templates/inventario/listaCategorias.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{%static 'css/modal.css'%}">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
{% endblock css %}

{% block content %}
<div class="container mt-5">

    <div class="container text-center mt-5">


        <div class="row">
            <div class="col-md-8 mt-2 d-flex">

                <h2 class="fst-italic ">Categorias</h2>
            </div>
            {% if perms.Inventario.add_product %}
            <div class="col-md-4 mt-2 d-flex justify-content-end">
                <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#creacion"><i
                        class="fas fa-plus"></i>
                    Crear Categoria
                </button>
            </div>
            {%endif%}
        </div>
        <div class="table-responsive mt-4">
            <table id="tabla_categorias" class="table table-bordered table-hover table-striped">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Descripcion</th>
                        <th>Foto</th>
                        <th>Productos</th>
                        {% if perms.Inventario.change_product or perms.Inventario.delete_product%}
                        <th>Acciones</th>
                        {%endif%}
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Modal Creacion -->
<div class="modal fade" id="creacion" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered ">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="creacion">Creacion de Categoria</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="POST" id="form_creacion">
                {% csrf_token %}
                <div class="modal-body">
                    {{form.as_p}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Confirmar</button>
                </div>
            </form>
        </div>
    </div>
</div>




{% endblock content%}
{% block extrajs %}
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="{% static 'js/productos/categorias.js' %}"></script>


{% endblock extrajs %}

templates/inventario/listaProductos.html
{% extends "base.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
{% endblock css %}

{% block content %}
<div class="container mt-5">

    <div class="container text-center mt-5">


        <div class="row">
            <div class="col-md-8 mt-2 d-flex">

                <h2 class="fst-italic ">Productos de la categoría </h2>
            </div>
            {% if perms.Inventario.add_product %}
            <div class="col-md-4 mt-2 d-flex justify-content-end">
                <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#creacion"><i
                        class="fas fa-plus"></i>
                    Crear Producto
                </button>
            </div>
            {%endif%}
        </div>
        <div class="table-responsive mt-4">
            <table id="tabla_productos" class="table table-bordered table-hover table-striped">
                <thead>
                    <tr>
                        <th>Codigo</th>
                        <th>Nombre</th>
                        <th>Stock</th>
                        <th>Precio</th>
                        {% if perms.Inventario.change_product or perms.Inventario.delete_product%}
                        <th>Acciones</th>
                        {%endif%}
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Modal Creacion -->
<div class="modal fade" id="creacion" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
    aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered ">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="creacion">Creacion de Producto</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <form method="POST" id="form_creacion">
                {% csrf_token %}
                <div class="modal-body">
                    {{form.as_p}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Confirmar</button>
                </div>
            </form>
        </div>
    </div>
</div>




{% endblock content%}
{% block extrajs %}
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="{% static 'js/productos/index.js' %}"></script>


{% endblock extrajs %}

templates/inventario/proveedores.html
{% extends "base.html" %}
{% load static %} 
{% block css %}
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" />
{% endblock css %} {% block content %}
<div class="container mt-5">
    <div class="container text-center mt-5">
        <div class="row">
            <div class="form-group col-md-8 mt-2 d-flex justify-content-center align-items-center">
                <h1 class="fst-italic">Proveedores</h1>
            </div>
            {% if perms.Inventario.add_suppliers %}
            <div class="col-md-4 mt-2 d-flex justify-content-end">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#Creacion">
                    Crear Proveedor
                </button>
            </div>
            {%endif%}
        </div>
        <div class="table-responsive mt-4">
            <table id="tabla_proveedores" class="table table-bordered table-hover table-striped">
                <thead class="thead-red">
                    <tr>
                        <th>Run</th>
                        <th>Nombre</th>
                        <th>Email</th>
                        <th>Celular</th>
                        {% if perms.Inventario.change_suppliers or perms.Inventario.delete_suppliers%}
                        <th>Acciones</th>
                        {%endif%}
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
    <!-- Modal Creacion-->
    <div class="modal fade" id="Creacion" tabindex="-1" aria-labelledby="exampleModalLabel" data-bs-backdrop="static"
        data-bs-keyboard="false" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">
                        <strong>Formulario de Registro</strong>
                    </h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST" autocomplete="off">
                        {% csrf_token %} {{ form.as_p}}
                        <div class="modal-footer">
                            <a href="{% url 'proveedores' %}" class="btn btn-3d btn-dark">Cancelar</a>
                            <button type="submit" class="btn btn-primary">Guardar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock content%} 
{% block extrajs %}
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>
<script src="{% static 'js/productos/proveedores.js' %}"></script>

{% endblock extrajs %}